version: "3"

services:
  postgres:
    image: postgres:11.2-alpine
    ports:
      - "5432:5432"
    networks:
      - some-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    
  
  web:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    ports: 
      - "8080:8080"
    networks:
      - some-net
      
networks:
  some-net:
    driver: bridge
